services:
  app:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./:/app
      - vendor_data:/app/vendor
      - caddy_data:/data
      - caddy_config:/config
    environment:
      SERVER_NAME: ":80"
      CADDY_GLOBAL_OPTIONS: auto_https disable_redirects
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    restart: unless-stopped
    volumes:
      - ./:/app
      - vendor_data:/app/vendor
    environment:
      QUEUE_CONNECTION: ${QUEUE_CONNECTION}
      REDIS_HOST: ${REDIS_HOST}
    depends_on:
      - db
      - redis
    healthcheck:
      disable: true

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:17-alpine
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  caddy_data: {}
  caddy_config: {}
  db_data:
    driver: local
  vendor_data: {}
  redis_data: {}