services:
    db:
        image: postgres:17-alpine
        shm_size: 128mb
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE}
        ports:
            - "5432:5432"
        volumes:
            - apcascat_db_data:/var/lib/postgresql/data

    adminer:
        image: adminer
        ports:
            - "8080:8080"

volumes:
    apcascat_db_data:
        driver: local
