services:
  app:
    build:
      context: .
      args:
        - APP_ENV=${APP_ENV}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./:/app
      - vendor_data:/app/vendor
      - caddy_data:/data
      - caddy_config:/config
    environment:
      SERVER_NAME: ":80"
      CADDY_GLOBAL_OPTIONS: auto_https disable_redirects
      TZ: Europe/Madrid
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  cron:
    build:
      context: .
      args:
        - APP_ENV=${APP_ENV}
    command: >
      sh -c "mkdir -p /etc/cron.d &&
      echo '* * * * * cd /app && /usr/local/bin/php artisan schedule:run >> /dev/null 2>&1' > /etc/cron.d/laravel-scheduler &&
      chmod 0644 /etc/cron.d/laravel-scheduler &&
      crontab /etc/cron.d/laravel-scheduler &&
      cron -f"
    volumes:
      - ./:/app
      - vendor_data:/app/vendor
    environment:
      TZ: Europe/Madrid
    depends_on:
      - app

  node:
    image: node:24-alpine
    working_dir: /app
    command: sh -c "\
      if [ ! -d node_modules ] || [ -z \"$(ls -A node_modules)\" ]; then \
        echo 'Installing dependencies...' && npm install; \
      fi && \
      npm run dev -- --host"
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    environment:
      TZ: Europe/Madrid
    ports:
      - "5173:5173"
    depends_on:
      - app

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  caddy_data: {}
  caddy_config: {}
  db_data:
    driver: local
  vendor_data: {}
